#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _a2_reg();
extern void _alphasynapse1_reg();
extern void _bkkca_reg();
extern void _bkkcasiz_reg();
extern void _cal_reg();
extern void _capool_reg();
extern void _capoolax_reg();
extern void _capoolSC_reg();
extern void _capoolsiz_reg();
extern void _casLC_reg();
extern void _cat_reg();
extern void _Exc_reg();
extern void _ExpSynCG_reg();
extern void _gap_reg();
extern void _iaax_reg();
extern void _iaSC_reg();
extern void _icasax_reg();
extern void _icasSC_reg();
extern void _icatax_reg();
extern void _icatSC_reg();
extern void _ikcaax_reg();
extern void _ikcaSC_reg();
extern void _ikcasiz_reg();
extern void _inaax_reg();
extern void _Inh_reg();
extern void _kd_reg();
extern void _kd2_reg();
extern void _kdrax_reg();
extern void _kdrSC_reg();
extern void _kdsiz_reg();
extern void _leak_reg();
extern void _leakax_reg();
extern void _na_reg();
extern void _nap2_reg();
extern void _nasiz_reg();
extern void _Nn_reg();
extern void _Nn_old_reg();
extern void _SKKCa_reg();
extern void _vcl_reg();
extern void _vecevent_reg();
extern void _VVClamp_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," a2.mod");
fprintf(stderr," alphasynapse1.mod");
fprintf(stderr," bkkca.mod");
fprintf(stderr," bkkcasiz.mod");
fprintf(stderr," cal.mod");
fprintf(stderr," capool.mod");
fprintf(stderr," capoolax.mod");
fprintf(stderr," capoolSC.mod");
fprintf(stderr," capoolsiz.mod");
fprintf(stderr," casLC.mod");
fprintf(stderr," cat.mod");
fprintf(stderr," Exc.mod");
fprintf(stderr," ExpSynCG.mod");
fprintf(stderr," gap.mod");
fprintf(stderr," iaax.mod");
fprintf(stderr," iaSC.mod");
fprintf(stderr," icasax.mod");
fprintf(stderr," icasSC.mod");
fprintf(stderr," icatax.mod");
fprintf(stderr," icatSC.mod");
fprintf(stderr," ikcaax.mod");
fprintf(stderr," ikcaSC.mod");
fprintf(stderr," ikcasiz.mod");
fprintf(stderr," inaax.mod");
fprintf(stderr," Inh.mod");
fprintf(stderr," kd.mod");
fprintf(stderr," kd2.mod");
fprintf(stderr," kdrax.mod");
fprintf(stderr," kdrSC.mod");
fprintf(stderr," kdsiz.mod");
fprintf(stderr," leak.mod");
fprintf(stderr," leakax.mod");
fprintf(stderr," na.mod");
fprintf(stderr," nap2.mod");
fprintf(stderr," nasiz.mod");
fprintf(stderr," Nn.mod");
fprintf(stderr," Nn_old.mod");
fprintf(stderr," SKKCa.mod");
fprintf(stderr," vcl.mod");
fprintf(stderr," vecevent.mod");
fprintf(stderr," VVClamp.mod");
fprintf(stderr, "\n");
    }
_a2_reg();
_alphasynapse1_reg();
_bkkca_reg();
_bkkcasiz_reg();
_cal_reg();
_capool_reg();
_capoolax_reg();
_capoolSC_reg();
_capoolsiz_reg();
_casLC_reg();
_cat_reg();
_Exc_reg();
_ExpSynCG_reg();
_gap_reg();
_iaax_reg();
_iaSC_reg();
_icasax_reg();
_icasSC_reg();
_icatax_reg();
_icatSC_reg();
_ikcaax_reg();
_ikcaSC_reg();
_ikcasiz_reg();
_inaax_reg();
_Inh_reg();
_kd_reg();
_kd2_reg();
_kdrax_reg();
_kdrSC_reg();
_kdsiz_reg();
_leak_reg();
_leakax_reg();
_na_reg();
_nap2_reg();
_nasiz_reg();
_Nn_reg();
_Nn_old_reg();
_SKKCa_reg();
_vcl_reg();
_vecevent_reg();
_VVClamp_reg();
}
